from cs50 import SQL
db = SQL("sqlite:///name of database")

favorite = input('Favorite: ')

rows = db.execute("SELECT * FROM favorites WHERE problem = 'Mario'")
# will execute the string as SQL
rows = db.execute("SELECT * FROM favorites WHERE problem = ?", favorite)
# will use the user input instead of mario
# ? is used as a place holder

for row in rows:
    print(row["Timestamp"])
# will print the time stamp of each entry where the favorite was mario

rows = db.execute("SELECT COUNT(*) AS n FROM favorites WHERE problem = 'Mario'")

for row in rows:
    print(row["n"])
# will print the number of entries for mario

row = rows[0]
print(row["n"])
#does the same as previous print function


# cs50 sql returns the SQL data as a dictionary for example the SQL command will return ______
                                                                                #       |_n__|
                                                                                #       |_38_|
# with n being the key and 38 the value in a dictionary made generated by python